name = 'voting-system'
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8000
[[d1_databases]]
binding = "DB"
database_name = "vote-system"
database_id = "832b59da-1bf5-45cf-b5d1-b4935b625394"
